language: go
go:
- 1.8
env:
  matrix:
    - PATH=/home/travis/gopath/bin:$PATH
  global:
    secure: RDzkDZYAqy0gmzCrATiPyjyD+9yBYt5h5VgPNlZX+L+jEOv8Cgi/swfKVp2VkKn+2RDaqqyr6mGYtYy4JS6KESp3KsSbbtyXu/dbi9oowsFF1/emwY0ysc5/uTx/Xz8UDZpyv4VSN+SBavu8sgNE0Ur5Vcs8Pzp9MDaCwxBfxpzijCuqOQj9W/RffTosc2jC1USXnUVZnhSa6H5jlfQWAiYVR30Khfj6nnbQYRIdlsmQJXwhysr8wSXplEAqENGKsx7ZuVXc/Z07cGqC6vOPZddGI90R6Upvavjc/uP4fml86K/tqC2U8V/5qSUxIdDylcIreguBlkwSLDWiosvAN9hq35oHXmNRFU1k+vYzj3iQkw2CXU4MOqpQWSsOoy9SnhjlRg2BQXVqlP4y6oOCgRWh/IhQ6Nhy4yAVVpktaZOGhvRw99i08Wi7J20gSmrvAZFrhIPArcX/uqfpBwM+ruQeGmbPne0y7z6mM9gQN4tK6ZausFVk6lS0Zr+2AUazqilgB+FMgVXSGinvxlB9G092c2rYn/1mehmTvqUD/pLPzkwq2JhVMHfMo3MewYu52nuO5Tr92hsInW8km8eYJCy8GoudNJK2x3+A1NdSqFhFv4d3Vn5Uj6M76zV/Xg8/TeWALPj6saNJqEjOm0GvBtCZPkhISVqoMXxUTyNIbqc=
before_install:
- go get github.com/mitchellh/gox
- go get github.com/tcnksm/ghr
script:
- go test -v
after_success:
- gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
- ghr --username pcfens --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/
